### ISSUE TITLE
The customer mandate is still pending

### ISSUE THREAD

**Issue by voicecode-bv** [mollie/laravel-cashier-mollie#172] opened 2023-04-21 05:08 UTC
Hi there,

As our app and number of subscribers grow every single day, some exceptions are shown more and more. For example the MandateIsNotYetFinalizedException(). 

Is there a specific action we need to take when this exception is thrown? Or is it safe to ignore this? 

Thanks! :)

Michael

**Comment by Naoray** [comment] 2023-04-22 09:22
Hi @voicecode-bv,

the `MandateIsNotYetFinalizedException` is thrown either when either you create a new [Charge](https://www.cashiermollie.com/04-charges.html) or when a `OrderPaymentFailed` was fired. Both of these occurrences are happening because your customer’s Mollie mandate is still `pending`. Which means that your client didn’t complete the order process/didn’t pay yet.

> The status of the mandate. A status can be pending for mandates when the first payment is not yet finalized or when we did not received the IBAN yet.

**Comment by wimski** [comment] 2023-05-26 12:29
And what would it mean if these errors start appearing through the `FirstPaymentWebhookController`?

```
Laravel\Cashier\Exceptions\MandateIsNotYetFinalizedException The customer mandate is still pending 
    vendor/mollie/laravel-cashier-mollie/src/Billable.php:473 App\Models\User::validateMollieMandate
    vendor/mollie/laravel-cashier-mollie/src/Billable.php:491 App\Models\User::guardMollieMandate
    vendor/mollie/laravel-cashier-mollie/src/SubscriptionBuilder/MandatedSubscriptionBuilder.php:94 Laravel\Cashier\SubscriptionBuilder\MandatedSubscriptionBuilder::create
    vendor/mollie/laravel-cashier-mollie/src/FirstPayment/Actions/StartSubscription.php:184 Laravel\Cashier\FirstPayment\Actions\StartSubscription::execute
    vendor/mollie/laravel-cashier-mollie/src/FirstPayment/FirstPaymentHandler.php:125 Laravel\Cashier\FirstPayment\FirstPaymentHandler::Laravel\Cashier\FirstPayment\{closure}
    vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php:245 Illuminate\Support\Collection::each
    vendor/mollie/laravel-cashier-mollie/src/FirstPayment/FirstPaymentHandler.php:126 Laravel\Cashier\FirstPayment\FirstPaymentHandler::executeActions
    vendor/mollie/laravel-cashier-mollie/src/FirstPayment/FirstPaymentHandler.php:47 Laravel\Cashier\FirstPayment\FirstPaymentHandler::Laravel\Cashier\FirstPayment\{closure}
    vendor/laravel/framework/src/Illuminate/Database/Concerns/ManagesTransactions.php:29 Illuminate\Database\Connection::transaction
    vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php:442 Illuminate\Database\DatabaseManager::__call
    vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:261 Illuminate\Support\Facades\Facade::__callStatic
    vendor/mollie/laravel-cashier-mollie/src/FirstPayment/FirstPaymentHandler.php:69 Laravel\Cashier\FirstPayment\FirstPaymentHandler::execute
    vendor/mollie/laravel-cashier-mollie/src/Http/Controllers/FirstPaymentWebhookController.php:26 Laravel\Cashier\Http\Controllers\FirstPaymentWebhookController::handleWebhook
    [...]
```

**Comment by Naoray** [comment] 2023-05-30 10:56
@wimski that’s odd. Which version of this package are you using?

**Comment by sandervanhooft** [comment] 2023-06-07 11:24
Hi @wimski and @voicecode-bv we're diving deeper into this. Can you share:

- the package version
- cashier configs (redacted if necessary)
- any customizations made (i.e. model overrides
- code used for triggering the payment (subscription builder/charge builder)
- if you have it: the specific payment method used

This way we can hopefully reproduce the issue here and/or trace it down

**Comment by sandervanhooft** [comment] 2023-06-12 10:37
Hi @patrick-zuurbier ,

Thank you. Are you seeing these exceptions both in testmode and live?

**Comment by sandervanhooft** [comment] 2023-06-12 10:39
Also, can you share how this was implemented?

```php
        InvalidMandateNoticedEvent::dispatchIf(
            ! hasValidMollieMandate($user),
            $user,
            'subscribe'
        );
```

**Comment by sandervanhooft** [comment] 2023-06-12 10:44
I may have found the culprit.

It seems like the exception gets thrown also when the mandate is null.

I suspect this check gets triggered prematurely in this integration with this snippet:

```php
        InvalidMandateNoticedEvent::dispatchIf(
            ! hasValidMollieMandate($user),
            $user,
            'subscribe'
        );
```

**Comment by sandervanhooft** [comment] 2023-06-12 10:44
@patrick-zuurbier can you check this?

**Comment by voicecode-bv** [comment] 2023-08-01 12:55
Hi all, 

We had the same issue again yesterday using the latest version of this repo. 
In the query log I see that there's actually a mandate being stored in the database:

`update
  `users`
set
  `mollie_mandate_id` = mdt_TvJRGBAMmB,
  `users`.`updated_at` = 2023 -07 -31 11: 23: 18
where
  `id` = *****`

**Comment by sandervanhooft** [comment] 2023-08-01 18:27
Hi @voicecode-bv , thanks for following up. Did you check my previous suggestion on your integration: https://github.com/mollie/laravel-cashier-mollie/issues/172#issuecomment-1587071870 ?

**Comment by sandervanhooft** [comment] 2023-10-02 11:46
Closing this for now, let me know if it should be reopened.

**Closed by sandervanhooft** 2023-10-02 11:46 UTC

**Comment by voicecode-bv** [comment] 2025-04-23 08:10
Hi @sandervanhooft, 

I'm currently investigating the cause of users starting a subscription multiple times causing them to have multiple of the same subscriptions. 

I guess I have to reopen this issue again. As you can see in the screenshot below, this still happens on first payments, in our case, quite often too. 

<img width="1246" alt="Image" src="https://github.com/user-attachments/assets/4d4f25ea-e24c-47ff-9cc3-b7f28d0aad5e" />

In Mollie I see the following 2 payments.

This one fails the first time because of a 500 error on the webhook. If you look at the timestamp (2025-04-17 22:16:25), it's because of the pending mandate. 

<img width="989" alt="Image" src="https://github.com/user-attachments/assets/943c8af9-63d7-405e-9e88-ee1155962d55" />

Then, another payment is created a minute later, with a different transaction ID but with the same order number. So I think its safe to assume that the customer thought subscribing failed and tried to subscribe again, resulting in 2 payments. 

<img width="991" alt="Image" src="https://github.com/user-attachments/assets/33f897a5-4c9f-48a7-8a7a-3edca0d96ac9" />

Can you please advise how to prevent this from happening? We've got a couple of thousand subscriptions, and as you can see this happens quite a lot. We have to refund all customers manually which is very time consuming to say the least ;-)
